// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final_Project_Assignment.Models
{
    public partial class Dmv
    {
        public Dmv()
        {
            Drivers = new HashSet<Driver>();
            Vehicles = new HashSet<Vehicle>();
        }

        public int DmvId { get; set; }
        public string DmvFirstName { get; set; }
        public string DmvLastName { get; set; }

        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}