// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final_Project_Assignment.Models
{
    public partial class DriverInfraction
    {
        public int DriverId { get; set; }
        public int InfractionId { get; set; }

        public virtual Driver Driver { get; set; }
        public virtual Infraction Infraction { get; set; }
    }
}