// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final_Project_Assignment.Models
{
    public partial class Law
    {
        public Law()
        {
            Vehicles = new HashSet<Vehicle>();
        }

        public int LawId { get; set; }
        public string LawFirstName { get; set; }
        public string LawLastName { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}