// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final_Project_Assignment.Models
{
    public partial class Vehicle
    {
        public int VehicleId { get; set; }
        public string VehicleName { get; set; }
        public int? VehicleYear { get; set; }
        public int? DriverId { get; set; }
        public int? DmvId { get; set; }
        public int? LawId { get; set; }

        public virtual Dmv Dmv { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Law Law { get; set; }
    }
}